name: Build & Push Image on Tag (ACR)

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: Dockerfile
    secrets:
      ACR_REGISTRY:
        required: true
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout CALLING repo code (important)
      - uses: actions/checkout@v4

      - name: Extract repo name & tag
        id: meta
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | \
          docker login ${{ secrets.ACR_REGISTRY }} \
            --username ${{ secrets.ACR_USERNAME }} \
            --password-stdin

      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.ACR_REGISTRY }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.TAG }}
          docker build -t $IMAGE -f ${{ inputs.dockerfile }} .

      - name: Push Docker image
        run: |
          IMAGE=${{ secrets.ACR_REGISTRY }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.TAG }}
          docker push $IMAGE

      - name: Logout
        run: docker logout ${{ secrets.ACR_REGISTRY }}
